# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\PIA_VISUALIZACION\entrada.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border–radius:20px;\n"
"\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 30, 181, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\netflix-logo-51.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(350, 480, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 480, 91, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 180, 341, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-radius:5px;")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32768)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 250, 341, 51))
        self.lineEdit_2.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-radius:5px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(32768)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 360, 341, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 320, 281, 20))
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color : red;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 420, 341, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 510, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 20, 181, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\../Cuarto Semestre/3-PROGRAMACION BASE DE DATOS/CATALOGOPELICULA/DATOSPROGRAMACION/netflix-logo-51.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e4e4e4;\">Need help?</span></p><p><span style=\" color:#e4e4e4;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#edf0f0;\">Remenber me</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "   Email or phone number"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "   Password"))
        self.pushButton.setText(_translate("MainWindow", "Sign In"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton_3.setText(_translate("MainWindow", "EXIT"))
