# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\PIA_VISUALIZACION\registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border–radius:20px;\n"
"\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 30, 181, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\netflix-logo-51.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_registro = QtWidgets.QPushButton(self.frame)
        self.pushButton_registro.setGeometry(QtCore.QRect(70, 540, 341, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_registro.setFont(font)
        self.pushButton_registro.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.pushButton_registro.setObjectName("pushButton_registro")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(200, 100, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 91, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(40, 190, 141, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(40, 220, 151, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(40, 310, 91, 31))
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(140, 320, 131, 21))
        self.comboBox.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 10pt \".AppleSystemUIFont\";\n"
"font: 10pt \".AppleSystemUIFont\";\n"
"font: 10pt \".AppleSystemUIFont\";\n"
"border-radius:5px;")
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(40, 270, 91, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(40, 410, 161, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(40, 450, 161, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(40, 490, 171, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(40, 360, 91, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(210, 150, 251, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32768)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 500, 251, 21))
        self.lineEdit_8.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 450, 251, 21))
        self.lineEdit_7.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 190, 251, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(32768)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 230, 251, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(32768)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 280, 251, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setMaxLength(32768)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 370, 251, 21))
        self.lineEdit_5.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(32768)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 410, 251, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"font: 11pt \".AppleSystemUIFont\";\n"
"border-radius:7px;")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(32768)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_registro_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_registro_2.setGeometry(QtCore.QRect(70, 580, 341, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_registro_2.setFont(font)
        self.pushButton_registro_2.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.pushButton_registro_2.setObjectName("pushButton_registro_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 181, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\../Cuarto Semestre/3-PROGRAMACION BASE DE DATOS/CATALOGOPELICULA/DATOSPROGRAMACION/netflix-logo-51.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_registro.setText(_translate("MainWindow", "Sign Up"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">REGISTRO</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Nombre (s):</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Apellido Paterno:</span></p><p><span style=\" font-size:10pt; color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Apellido Materno:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Género:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Hombre"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Mujer"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Edad:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Correo:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Contraseña:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Confirmar Contraseña:</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Celular:</span></p></body></html>"))
        self.pushButton_registro_2.setText(_translate("MainWindow", "Back"))
