# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\PIA_VISUALIZACION\siniestro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1256, 661))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(60, 90, 271, 341))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\imagenes/fenomenoSiniestrosinopsis.jpg"))
        self.label.setScaledContents(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.labelBienvenida = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida.setGeometry(QtCore.QRect(370, 120, 241, 61))
        self.labelBienvenida.setStyleSheet("color:white;")
        self.labelBienvenida.setObjectName("labelBienvenida")
        self.labelBienvenida_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_2.setGeometry(QtCore.QRect(370, 240, 241, 61))
        self.labelBienvenida_2.setStyleSheet("color:white;")
        self.labelBienvenida_2.setObjectName("labelBienvenida_2")
        self.labelBienvenida_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_3.setGeometry(QtCore.QRect(850, 100, 241, 61))
        self.labelBienvenida_3.setStyleSheet("color:white;")
        self.labelBienvenida_3.setObjectName("labelBienvenida_3")
        self.labelLogo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelLogo.setGeometry(QtCore.QRect(520, 20, 171, 51))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("c:\\Users\\angel\\Desktop\\PIA_VISUALIZACION\\imagenes/netflix-logo-51.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.labelBienvenida_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_4.setGeometry(QtCore.QRect(760, 150, 421, 41))
        self.labelBienvenida_4.setStyleSheet("color:white;")
        self.labelBienvenida_4.setObjectName("labelBienvenida_4")
        self.labelBienvenida_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_5.setGeometry(QtCore.QRect(370, 350, 241, 61))
        self.labelBienvenida_5.setStyleSheet("color:white;")
        self.labelBienvenida_5.setObjectName("labelBienvenida_5")
        self.labelBienvenida_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_6.setGeometry(QtCore.QRect(100, 440, 191, 31))
        self.labelBienvenida_6.setStyleSheet("color:white;")
        self.labelBienvenida_6.setObjectName("labelBienvenida_6")
        self.labelBienvenida_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_7.setGeometry(QtCore.QRect(320, 440, 371, 101))
        self.labelBienvenida_7.setStyleSheet("color:white;")
        self.labelBienvenida_7.setObjectName("labelBienvenida_7")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(720, 270, 491, 331))
        self.textEdit.setStyleSheet("\n"
"background-color: rgb(186, 186, 186);")
        self.textEdit.setObjectName("textEdit")
        self.labelBienvenida_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelBienvenida_8.setGeometry(QtCore.QRect(760, 230, 421, 31))
        self.labelBienvenida_8.setStyleSheet("background-color: rgb(175, 175, 175);\n"
"")
        self.labelBienvenida_8.setObjectName("labelBienvenida_8")
        self.bot_resena = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bot_resena.setGeometry(QtCore.QRect(110, 600, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.bot_resena.setFont(font)
        self.bot_resena.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.bot_resena.setObjectName("bot_resena")
        self.bot_regresar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bot_regresar.setGeometry(QtCore.QRect(340, 600, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.bot_regresar.setFont(font)
        self.bot_regresar.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(240, 0, 27);\n"
"Color: white;")
        self.bot_regresar.setObjectName("bot_regresar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelBienvenida.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">FECHA DE ESTRENO</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">03/02/2012</span></p></body></html>"))
        self.labelBienvenida_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">GENERO:</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">TERROR</span></p></body></html>"))
        self.labelBienvenida_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">PELICULA</span></p></body></html>"))
        self.labelBienvenida_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">FENOMENO SINIESTRO</span></p></body></html>"))
        self.labelBienvenida_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">SINOPSIS:</span></p></body></html>"))
        self.labelBienvenida_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'arial,sans-serif\'; font-size:9pt; color:#cfcfcf;\">B-15</span><span style=\" font-family:\'arial,sans-serif\'; font-size:9pt; color:#cfcfcf; background-color:#202124;\"> 2011 ‧ Terror ‧ 1h 35m</span></p></body></html>"))
        self.labelBienvenida_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:9pt; color:#e5e5e5;\">Un equipo de cazadores de fantasmas graba un episodio <br/>para un show televisivo dentro de un hospital psiquiátrico<br/>abandonado, luego de varios reportes de extraños <br/>fenómenos</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelBienvenida_8.setText(_translate("MainWindow", "<html><head/><body bgcolor= \"white\"><p align=\"center\"><span style=\" font-size:11pt; color:#00000;\">RESEÑAS</span></p></body></html>"))
        self.bot_resena.setText(_translate("MainWindow", "ESCRIBIR RESEÑA"))
        self.bot_regresar.setText(_translate("MainWindow", "REGRESAR"))
